name: PRSADD187
display_name: PRSADD187
version: 1.0.0
author:
  name: "TemplateMela"
  email: "support@templatemela.com"
  url: "http://www.templatemela.com"

meta:
  compatibility:
      from: 1.7.0.0
      to: 1.7.4.4

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Two Columns
      description: Two columns with a small left column
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
#  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
   css:
     all:
      - id: fontawesome-lib-style
        path: assets/css/font-awesome.css
      - id: animate-lib-style
        path: assets/css/animate.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
   js:
     all:
       - id: owl-carousel-lib
         path: assets/js/owl.carousel.js
         priority: 310
         position: bottom
       - id: totalstorage-lib
         path: assets/js/totalstorage.js
         priority: 330
         position: bottom
         position: bottom
       - id: lightbox
         path: assets/js/lightbox.js
       - id: inview
         path: assets/js/inview.js
         priority : 370
         position: bottom 
#    cart:
#      - id: cat-extra-lib
#        path: assets/js/cart-lib.js


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
   to_enable:
     - ps_linklist
   to_disable:
     - ps_imageslider
  hooks:
    modules_to_hook:
      displayNav1:
      displayNav2:
      displayTopAbove:
       - tm_toplink
       - ps_shoppingcart
       - ps_customersignin
       - ps_languageselector
       - ps_currencyselector
      displayTop:
       - tm_servicecmsblock
       - ps_searchbar
       - tm_nav1cmsblock
      displayTopColumn:
       - tm_imageslider
       - tm_cms1block
       - tm_categorylist
      displayHome:
       - tm_cmsblock
       - tm_specials
       - tm_cmsbannerblock
       - tm_categoryslider
      displaySpecialBanner:
       - tm_cms3block
      displayTmHoverImage:
       - tm_imagehover
      displayTmFeature:
       - tm_featuredproducts
      displayTmBestseller:
       - tm_bestsellers
      displayTmNew:
       - tm_newproducts
      displayHomeBottom:
       - tm_testimonialcmsblock
      displayFooterBefore:
       - ps_emailsubscription
       - ps_socialfollow
      displayFooter:
        - ps_contactinfo
        - ps_linklist
        - tm_aboutcmsblock
      displayFooterAfter:
        - tm_footerlink
        - tm_paymentcmsblock
      displayLeftColumn:
        - tm_verticalmenu
        - ps_facetedsearch
        - tm_leftbanner
        - tm_sidenewproducts
        - tm_blocklink
        - tm_leftbanner1
        - tm_sidefeaturedproducts
      displayLeftColumnProduct:
        - ps_categorytree
        - tm_sidenewproducts
        - tm_sidefeaturedproducts
      displayRightColumn:
      displayRightColumnProduct:
      displaySearch:
        - ps_searchbar
      displayProductButtons:
        - ps_sharebuttons
      displayReassurance:
      displayFooterProduct:
      displayProductListReviews:
      displayRightColumnProduct:

  image_types:
    cart_default:
      width: 66
      height: 78
      scope: [products]
    small_default:
      width: 98
      height: 97
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 447
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 265
      height: 262
      scope: [products]
    large_default:
      width: 599
      height: 592
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 1118
      height: 200
      scope: [categories]
    stores_default:
      width: 170
      height: 168
      scope: [stores]
    special_default :
      width: 334
      height: 330
      scope: [products]

theme_settings:
  default_layout: layout-both-columns
  layouts:
    index: layout-both-columns
    product: layout-both-columns
    category: layout-both-columns
    cart: layout-left-column
    checkout: layout-left-column

dependencies:
  modules:
    - tm_toplink
    - tm_servicecmsblock
    - tm_nav1cmsblock
    - tm_imageslider
    - tm_cms1block
    - tm_categorylist
    - tm_cmsblock
    - tm_specials
    - tm_cmsbannerblock
    - tm_categoryslider
    - tm_cms3block
    - tm_imagehover
    - tm_featuredproducts
    - tm_bestsellers
    - tm_newproducts
    - tm_testimonialcmsblock
    - tm_aboutcmsblock
    - tm_footerlink
    - tm_paymentcmsblock
    - tm_verticalmenu
    - tm_leftbanner
    - tm_blocklink
    - tm_leftbanner1
    - tm_sidenewproducts
    - tm_sidefeaturedproducts